spring:
  profiles:
    active: 
    - dev
    
---

spring:
  profiles: dev
  application:
     name: microservicecloud-config-chinasoft-dev
     
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-chinasoft-test